server:
  port: ${PORT:8761}
  
 
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
  instance:
    hostname: "${HOSTNAME}.eureka"
    leaseRenewalIntervalInSeconds: 10
 
